In [2]:
import numpy as np

Array Numpy(Lista Otimizada)

In [2]:
numeros = [2,4,8,16,32,64,128]

array_numeros = np.array(numeros)

array_numeros

array([  2,   4,   8,  16,  32,  64, 128])

<b> Operações Vetorizadas </b>

#numeros +2 --> Com uma lista normal da erro
for numero in numeros:
    print(numero * 2)

print(array_numeros * 2)

Comparações Vetorizadas


In [4]:
array_aleatorios = np.array([22,12,13,14,54,23,25,75])
print(array_aleatorios % 2 == 0)

[ True  True False  True  True False False False]


Filtro condicional

In [5]:
print("Maiores que 20: ", array_aleatorios[array_aleatorios > 20]) # Mostra apenas os valores maiores que 20
print("Pares: ", array_aleatorios[array_aleatorios % 2 == 0]) # Mostra apenas os valores pares
print("Ímapares: ", array_aleatorios[array_aleatorios % 2 ==1]) # Mostra apenas os valores ímpares

Maiores que 20:  [22 54 23 25 75]
Pares:  [22 12 14 54]
Ímapares:  [13 23 25 75]


<b> Operações com Arrays </b>

In [10]:
print(array_aleatorios)
print("Soma",np.sum(array_aleatorios))
print("Média",np.mean(array_aleatorios))
print("Mínimo",np.min(array_aleatorios))
print("Máximo",np.max(array_aleatorios))

[22 12 13 14 54 23 25 75]
Soma 238
Média 29.75
Mínimo 12
Máximo 75


<h3> Lista de Exercícios </h3>

<h2> Exercício 2 </h2>

In [13]:
array_numeros = np.array([1,2,3,4,5])
print(array_numeros * 2)
print(array_numeros + 10)
print(array_numeros ** 2)

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


<h2> Exercício 3 </h2>

In [43]:
notas = np.array([7.5, 8.0, 6.5, 9.0, 5.5])
print("Média",np.mean(notas))

Média 7.3


<h2> Exercício 4 </h2>

In [42]:
numeros = np.array([10,20,30,40,50])

print(numeros / np.max(numeros))

[0.2 0.4 0.6 0.8 1. ]


<h2> Exercício 5 </h2>

In [41]:
numeros = np.array([15,18,22,17,30,16])

print(numeros [ (numeros > 10) & (numeros < 25)])

[15 18 22 17 16]


<h2> Exercício 6 </h2>

In [40]:
numeros = np.array([5,10,15,20,25,30])

print(numeros[numeros >= 10], [numeros <= 25])

[10 15 20 25 30] [array([ True,  True,  True,  True,  True, False])]


<h2> Exercício 7 </h2>

In [39]:
numeros = np.array([4,6,7,5,8,3,9])

total = np.sum(numeros >= 6)

print(total)

4


<h2> Exercício 8 </h2>

In [4]:
salarios = np.array([1000, 2000, 3000, 1500])

salarios[salarios < 2000] += 500

print(salarios)

[1500 2000 3000 2000]


<h2> Exercício 9 </h2>

In [3]:
precos = np.array([10,20,30,40])

precos = precos * 1.1

print(precos)

[11. 22. 33. 44.]


<h2> Exercício 10 </h2>

In [7]:
valores = np.array([10, 20, 30, 40, 50])

media = np.mean(valores[valores > 25])

print(media)

40.0


<h2> Exercício 11 </h2>

In [18]:
idades = np.array([18, 25, 30, 22, 40])
salarios = np.array([2000, 3000, 4000, 2500, 5000])

media = np.mean(salarios[idades > 25])

print(media)

4500.0


In [19]:
print(idades > 25)
print(salarios)

print(salarios[idades > 25])

[False False  True False  True]
[2000 3000 4000 2500 5000]
[4000 5000]


<h2> Exercício 12 </h2>

In [3]:
valores = np.array([5, 7, 8, 4, 9])

indice = np.where(valores >= 7 )

print(indice[0])

[1 2 4]


<h2> Exercício 13 </h2>

In [29]:
numeros = np.array([1,2,3,4,5,6,7,8,9,10])

pares = numeros[numeros % 2 == 0]

print(pares)

[ 2  4  6  8 10]


<h2> Exercício 14 </h2>

In [5]:
from random import randint
lista_aleatorios = [randint(1,100) for i in range(10)]
lista_aleatorios

[89, 48, 79, 88, 4, 63, 61, 70, 48, 66]

In [41]:

numeros = np.array([11,28,69,59,47,35,5,98,74,19])

media = np.mean(numeros)
print(media)
print(numeros[numeros > media]) 

44.5
[69 59 47 98 74]


<h2> Exercício 15 </h2>

In [44]:
notas = np.array([5, 7, 8, 6, 4, 9, 10])

media = np.mean(notas)
print(media)

len(notas[notas > media])

7.0


3